src/Numerics/Differentiation/FiniteDifferenceCoefficients.cs
src/Numerics/Differentiation/NumericalDerivative.cs
src/Numerics/Differentiation/NumericalHessian.cs
src/Numerics/Differentiation/NumericalJacobian.cs
src/Numerics/Numerics.csproj
src/UnitTests/DifferentiationTests/FiniteDifferenceCoefficientsTests.cs
src/UnitTests/DifferentiationTests/NumericalDerivativeTests.cs
src/UnitTests/DifferentiationTests/NumericalHessianTests.cs
src/UnitTests/DifferentiationTests/NumericalJacobianTests.cs
src/UnitTests/UnitTests.csproj

This is a pull request fulfilling #135 plus more features. 
I added support for numerical differentiation by creating two main components. A finite difference coefficients class and a numerical derivative class. As the name suggests, `FiniteDifferenceCoefficients` generates the coefficients necessary for numerical differentiation. For a given number of points, It pre-computes and stores all possible derivative orders and different centerings. This provides maximum flexibility (not restricted to forward, backward, center). See http://en.wikipedia.org/wiki/Finite_difference_coefficient .
Built on top of that is `NumericalDerivative` which uses the previous class to evaluate functions. It supports various step size types and I've included a few helper methods that give back derivative …

Numerical Differentiation Support

---

src/Numerics/Distributions/ChiSquared.cs
src/UnitTests/DistributionTests/Continuous/ChiSquareTests.cs

Utility method to get the quantiles for the chisquared distribution. This can be done through the gamma distribution, but this is a bit nicer.
Also added a unit test

chisquared inverse distribution

---

src/NativeProviders/ATLAS/blas.c
src/NativeProviders/ATLAS/lapack.cpp
src/NativeProviders/MKL/blas.c
src/NativeProviders/MKL/lapack.cpp
src/NativeProviders/MKL/memory.c
src/NativeProviders/MKL/vector_functions.c
src/NativeProviders/OSX/mkl_build.sh
src/NativeProviders/Windows/ATLAS/ATLASWrapper.vcxproj

Updated the partial ATLAS provider to the cleaner LAPACK code and added a OSX MKL build script.

Minor Native Tweaks

---

src/Numerics/Numerics.csproj
src/Numerics/Optimization/MinimizationResult.cs
src/Numerics/Optimization/NelderMeadSimplex.cs
src/UnitTests/OptimizationTests/NelderMeadSimplexTests.cs
src/UnitTests/UnitTests.csproj

I needed the Nelder-Mead simplex algorithm and found an MIT licensed version [here](https://code.google.com/p/nelder-mead-simplex/). I've adapted this to fit into the unified-optimization branch. Maybe not the best idea to add something to a branch that is "work-in-progress" but since it was a quite small addition I thought it was worth the effort anyway :-).
The Nelder-Mead simplex algorithm is probably mainly known as [fminsearch()](http://se.mathworks.com/help/matlab/math/optimizing-nonlinear-functions.html#bsgpq6p-11) in Matlab and is quite useful when you need to do a minimization and don't have access to the gradient/or if it's expensive to calculate.

Nelder-Mead simplex algorithm (unified optimization)

---

src/FSharp/FSharp-Net35.fsproj
src/FSharp/FSharp.fsproj
src/FSharp/Quaternion.fs
src/FSharpUnitTests/FSharpUnitTests-Net35.fsproj
src/FSharpUnitTests/FSharpUnitTests.fsproj
src/FSharpUnitTests/QuaternionTests.fs
src/UnitTests/UnitTests-Net35.csproj

Here is an FSharp implementation of a Quaternion.  Please let me know if I am missing anything according to contribution guidelines.  I have tried to include references for where I found my math.

Added Quaternion and QuaternionTests to the FSharp project

---

src/Data/Text/DelimitedReader.cs

before
after
test file is a 3700*3700 matrix, 385MB.

improve memory usage of parsing.

---

src/Numerics/Numerics.csproj
src/Numerics/OdeSolvers/OdeSolvers.cs
src/UnitTests/OdeSolvers/OdeSolverTest.cs
src/UnitTests/UnitTests.csproj

Recently, I have worked on the ode solver, such as Runge-Kutta(RK) method. 
I think that ode solver library is essential, because an ordinary differential equation frequently appears in Numerical Analysis.
So far, I've done with
1. RK2(Single ODE)
1. RK4(Single ODE)
1. RK2(ODE system)
1. RK4(ODE system)
To verify its accuracy and error convergence, I added two tests 
1. RK2 should have second order convergence order given test problem
1. RK4 should have fourth order convergence order given test problem
Tests are successful, so I make this pull request.
If you have any opinion and comments, let me know.

ODE Solvers(RK2 & RK4)

---

src/Numerics/LinearAlgebra/Complex/Vector.cs
src/Numerics/LinearAlgebra/Complex32/Vector.cs
src/Numerics/LinearAlgebra/Double/DenseVector.cs
src/Numerics/LinearAlgebra/Double/Vector.cs
src/Numerics/LinearAlgebra/Single/DenseVector.cs
src/Numerics/LinearAlgebra/Single/Vector.cs
src/Numerics/LinearAlgebra/Vector.Arithmetic.cs

"returns Index of absolute maximum -> returns Index of Maximum"

fixed documentation of Vector.MaximumIndex()

---

src/Numerics/LinearAlgebra/Complex/SparseMatrix.cs
src/Numerics/LinearAlgebra/Complex32/SparseMatrix.cs
src/Numerics/LinearAlgebra/Double/SparseMatrix.cs
src/Numerics/LinearAlgebra/Single/SparseMatrix.cs

Directly address underlying data-array for multiplying sparse with dense matrices with DenseColumnMajorMatrixStorage

Multiplying sparse with dense matrices with DenseColumnMajorMatrixStorage

---

src/Numerics/Statistics/Correlation.cs
src/UnitTests/StatisticsTests/CorrelationTests.cs

There was an incorrect formula in the weighted correlation method.  I have corrected it, I have added a unit test which would fail in the previous case but it passes now.

Correlation

---

src/Numerics/Providers/LinearAlgebra/ManagedLinearAlgebraProvider.Complex.cs
src/Numerics/Providers/LinearAlgebra/ManagedLinearAlgebraProvider.Complex32.cs
src/Numerics/Providers/LinearAlgebra/ManagedLinearAlgebraProvider.Double.cs
src/Numerics/Providers/LinearAlgebra/ManagedLinearAlgebraProvider.Single.cs

See https://github.com/mathnet/mathnet-numerics/issues/424

Fix recursion issue of CacheObliviousMatrixMultiply

---

src/Numerics/Trigonometry.cs
src/UnitTests/TrigonometryTest.cs

Updated some (hyperbolic) trig functions

---

src/Numerics/Distributions/ConwayMaxwellPoisson.cs
src/Numerics/Providers/LinearAlgebra/ManagedLinearAlgebraProvider.Complex32.cs

The variables are only used inside a conditional scope, so I moved the variables inside those scopes.

Move variables into scopes

---

src/Numerics.Tests/OptimizationTests/NelderMeadSimplexTests.cs
src/Numerics/Optimization/NelderMeadSimplex.cs

As discussing in #632 this is a pull request to solve #501 in the way suggested by @EricScottSalem.
Test taken from #501 by @MMAvanEnkhuizen

Improve convergence for symmetrical functions for Nelder Mead Simplex

---

src/Numerics.Tests/WindowTest.cs
src/Numerics/Window.cs

Hi,
I am working for Philips and we intend to use MathNet.Numerics in one of our products and contribute some of the extensions we require back to the community. I'd like to start with this very simple extension to the available window functions: The Tukey window.
Regards, Marco Ross.

Implemented and tested Tukey window

---

.paket/Paket.Restore.targets
src/Numerics.Tests/OptimizationTests/BfgsBMinimizerTests.cs
src/Numerics/Optimization/BfgsBMinimizer.cs

Detect early completion in BfgsBMinimizer

---

src/Numerics.Tests/DistributionTests/CommonDistributionTests.cs
src/Numerics.Tests/DistributionTests/Continuous/BurrTests.cs
src/Numerics.Tests/DistributionTests/Continuous/InverseGaussianTests.cs
src/Numerics.Tests/DistributionTests/Continuous/TruncatedParetoTests.cs
src/Numerics/Distributions/Burr.cs
src/Numerics/Distributions/InverseGaussian.cs
src/Numerics/Distributions/TruncatedPareto.cs
src/Numerics/Precision.Comparison.cs
src/Numerics/Properties/Resources.Designer.cs
src/Numerics/Properties/Resources.resx

Hello,
I added a few new distributions to the library.
- New distributions are
- Three parameter Burr (Type XII)
- Inverse Gaussian
- Truncated Pareto
- Unit tests added for all public methods
- New distributions added to CommonDistributionTests
I also added a new helper method (IsFinite) to Precision.Comparison. This was the most fitting place I could find, so I hope this is deemed appropriate.
Here some mathematical references for the added distributions:
- Burr:
- https://www.mathworks.com/help/stats/burr-type-xii-distribution.html
- [On the Three-Parameter Burr Type XII Distribution](https://www.researchgate.net/publication/275343043_On_the_Three-Parameter_Burr_Type_XII_Distribution_and_its_Application_to_Heavy_Tailed_Lifetime_Data)
- Inverse Gaussian
- …

Added new distributions and corresponding tests

---

docs/content/Functions.md

I think someone forgot a few logarithms.

fixed typo

---

.paket/Paket.Restore.targets
src/Numerics.Tests/OptimizationTests/NonLinearCurveFittingTests.cs
src/Numerics/Optimization/ObjectiveFunctions/NonlinearObjectiveFunction.cs

Fix incorrect weighted Jacobian in NonlinearObjectiveFunction

---

RELEASENOTES.md
src/Numerics.Tests/FractionalCalculusTests/RiemannLiouvilleTests.cs
src/Numerics/DifferIntegrate.cs
src/Numerics/Integrate.cs

The Riemann–Liouville fractional derivative is added.
References:
- [Differintegral](https://en.wikipedia.org/wiki/Differintegral)
- [Fractional Calculus](https://en.wikipedia.org/wiki/Fractional_calculus)

Fractional calculus

---

.gitignore
src/Numerics/Distributions/BetaBinomial.cs
src/Numerics/Distributions/Binomial.cs
src/Numerics/SpecialFunctions/GeneralizedHyperGeometric.cs

Adding the Beta-Binomial distribution. [https://en.wikipedia.org/wiki/Generalized_hypergeometric_function](https://en.wikipedia.org/wiki/Beta-binomial_distribution)
Also added the Generalized Hypergeometric Function as I thought it was required for calculating the CDF. However, most implementations just traverse over the PMF and sum. (Plus, I don't think Wikipedia is correct in the stated formula for the CDF). [https://en.wikipedia.org/wiki/Generalized_hypergeometric_function](https://en.wikipedia.org/wiki/Generalized_hypergeometric_function)
This also required adding the Rising and Falling Factorials [https://en.wikipedia.org/wiki/Falling_and_rising_factorials](https://en.wikipedia.org/wiki/Falling_and_rising_factorials)

Beta-Binomial distribution, and related functions

---

src/Numerics.Tests/LinearAlgebraTests/MatrixStructureTheory.cs
src/Numerics/LinearAlgebra/Builder.cs
src/Numerics/LinearAlgebra/Storage/SparseCompressedRowMatrixStorage.cs

Issue#721 - not-sorted and duplicate entries of COO format

---

src/Numerics.Tests/PrecisionTest.cs
src/Numerics/Precision.cs

Extension method to allow easy rounding of numerics

Add extension methods that allow round above zero

---

src/Numerics.Tests/DistributionTests/CommonDistributionTests.cs
src/Numerics.Tests/DistributionTests/Continuous/LogisticTests.cs
src/Numerics/Distributions/Logistic.cs

Adding the Logistic distribution: https://en.wikipedia.org/wiki/Logistic_distribution
I've tried to follow the pattern of the `Normal` distribution in the class and it's tests. 
The unit test distribution function validation values are from the equivalent functions in R.

Logistic distribution

---

src/Numerics/Optimization/LevenbergMarquardtMinimizer.cs
src/Numerics/Optimization/NonlinearMinimizerBase.cs
src/Numerics/Optimization/TrustRegion/TrustRegionMinimizerBase.cs

Please review this. Refer to #672.

Remove static properties in LevenbergMarquardtMinimizer

---

src/Numerics.Tests/PolynomialTests.cs
src/Numerics.Tests/StatisticsTests/DescriptiveStatisticsTests.cs
src/Numerics/Polynomial.cs
src/Numerics/Statistics/DescriptiveStatistics.cs

add JsonInclude for Polynomial and DescriptiveStatistics

---

src/Numerics.Tests/SpecialFunctionsTests/MarcumQTests.cs
src/Numerics/SpecialFunctions/MarcumQ.cs

Added the Marcum-Q function to SpecialFunctions and its tests to SpecialFunctionsTests.
The paper and the original implementation code can be found at the following URL
https://dl.acm.org/doi/abs/10.1145/2591004

add Marcum-Q function

---

src/Numerics.Tests/SpecialFunctionsTests/SpecialFunctionsTests.cs
src/Numerics/SpecialFunctions/Log1p.cs

Added log1p function and its test to SpecialFunctions.
The comparison values used in the test refer to the results of julia.

add log1p function

---

src/Numerics.Tests/Random/RandomExtensionTests.cs
src/Numerics/Random/RandomExtensions.cs

I'd like to add support for System.Numerics.BigInteger number type on random generation

RandomExtensions.NextBigIntegerSequence

---

src/Numerics/LinearAlgebra/Matrix.cs
src/Numerics/LinearAlgebra/Vector.cs

Looks like this:
Previous display for vector to compare:

Add debugger display proxy to vector and matrix
