- src/Data/Text/DelimitedReader.cs
- src/Data/Text/DelimitedWriter.cs
- src/DataUnitTests/Text/DelimitedReaderTests.cs
- src/DataUnitTests/Text/DelimitedWriterTests.cs
The reader on average should be about 15% slower. There should be no performance difference on the writer
> Added support for missing values to delimited reader and writter

- src/NativeProviders/MKL/lapack.cpp
- src/Numerics/Providers/LinearAlgebra/Mkl/MklLinearAlgebraProvider.Complex.cs
- src/Numerics/Providers/LinearAlgebra/Mkl/MklLinearAlgebraProvider.Complex32.cs
- src/Numerics/Providers/LinearAlgebra/Mkl/MklLinearAlgebraProvider.Double.cs
- src/Numerics/Providers/LinearAlgebra/Mkl/MklLinearAlgebraProvider.Single.cs
- src/UnitTests/LinearAlgebraTests/Complex/Factorization/EvdTests.cs
- src/UnitTests/LinearAlgebraTests/Complex/Factorization/UserEvdTests.cs
- src/UnitTests/LinearAlgebraTests/Complex32/Factorization/EvdTests.cs
- src/UnitTests/LinearAlgebraTests/Complex32/Factorization/UserEvdTests.cs
Simplified the LAPACK code by replacing the explicit function pointers definitions with template type deduction. It worked well, since it was able to deduce the correct values for complex eigen factorization - so the provider now supports it. Hopefully, this will simplify adding other providers. I'll try to add an Accelerate Framework/veclib provider and see if we can generalize the code a bit more.
I also added the non-convergence check on the native return value for SVD and eigen.
> Native Tweaks

- src/Numerics/Numerics.csproj
- src/Numerics/Providers/LinearAlgebra/Mkl/MklLinearAlgebraProvider.cs
- src/Numerics/Providers/LinearAlgebra/Mkl/SafeNativeMethods.cs
- src/Numerics/Providers/NativeProviderLoader.cs
- src/UnitTests/UnitTests-MKL.csproj
Added NativeProviderLoader, a helper class for loading native provider libraries depending on the processor architecture and the process bitness. MklLinearAlgebraProvider modified to call the helper class in InitializeVerify.
Not sure exactly how to automate building AnyCPU build though as both x86 and x64 builds need to be built first and then the files copied into subdirectories (x86 and amd64) of the AnyCPU output directory.
New nuget package for for combined x86 and x64 MKL will be needed. Couldn't find the nuspec though.
> Detect processor architecture and process bitness for loading native providers

- MathNet.Numerics.NativeProviders.sln
- src/Numerics/Providers/NativeProviderLoader.cs
- src/UnitTests/UnitTests-MKL.csproj
Couple of fixes to problems I found with the `NativeProviderLoader`.
* Couldn't find / load library dependencies in the architecture directory -> changed to `LoadLibraryEx`
* MSTest / Xunit would fail to locate the native library due to copying assemblies to Temp -> look in `AppDomain.Current.BaseDirectory` as well as `Assembly.GetExecutingAssembly().Location`.
> Native provider loader fixes

- src/Numerics/Distributions/ChiSquared.cs
This was resolved by using the GammaLowerRegularized function straight from the ChiSquared CDF method instead of division and multiplication by Gamma function.
Issue:
https://github.com/mathnet/mathnet-numerics/issues/288
> When DF parameter was high, the CDF returned NaN value. 

- src/Numerics/LinearAlgebra/Complex/SparseVector.cs
- src/Numerics/LinearAlgebra/Complex32/SparseVector.cs
- src/Numerics/LinearAlgebra/Double/SparseVector.cs
- src/Numerics/LinearAlgebra/Single/SparseVector.cs
The _type-specific_ SparseVector implementations **DID NOT** have AbsoluteMaximumIndex overrides although they **DO** have AbsoluteMinimumIndex overrides.
From the erroneous comment headers for MaximumIndex (which immediately follows AbsoluteMinimumIndex in the Double/ and Single/ files), it _appears_ that the implementations were all removed accidentally.
> Add (restore?) the missing SparseVector.AbsoluteMaximumIndex() override implementations

- src/Numerics/Statistics/Histogram.cs
- src/UnitTests/StatisticsTests/HistogramTests.cs
When using Histogram on a set of small doubles, I observed that the buckets were not sorting properly, which resulted in GetBucketIndexOf() throwing ArgumentExceptions before my Histogram was even constructed. 
I believe that the root issue here was that CompareTo() is using AlmostEqual() to compare bucket locations, which limits the resolution of the buckets to Precision.DefaultDoubleAccuracy
This request adds a set of unit test for small values, and safely moves the CompareTo function to .Equals().
> Small value histogram

- build/MathNet.Numerics.CUDA.Win.targets
- build/MathNet.Numerics.MKL.Win.targets
- build/MathNet.Numerics.OpenBLAS.Win.targets
The 'Copy' and 'Delete' tasks will only work for a project which is directly executed (an executable). It won't work for any projects which reference the project which includes one of the MathNet nuget packages (such as a unit test project). Installer projects such as WiX or VS Setup projects similarly won't find the required library files unless they are 'Content'.
> Change Nuget targets to use 'Content' rather than 'Copy' and 'Delete'

- src/Numerics/Distributions/Beta.cs
A beta PERT derives the shape parameters from the min, max, and mode -- this is often used in risk analysis, disease management, and other domains where an expert forecast or assessment is required.
This PR adds a static PERT method to the Beta class to instantiate a beta distribution from the min, max, and mode parameters. Note that I named the mode parameter "likely" to better match other libraries but would be happy to rename.
> Add a method to construct a beta PERT distribution

- src/Numerics/Numerics.csproj
- src/Numerics/RootFinding/Secant.cs
- src/UnitTests/RootFindingTests/SecantTest.cs
- src/UnitTests/UnitTests.csproj
The unit tests had to be modified slightly, because the Secant method supports two initial guesses while still maintaining lowerBound and upperBound. It's possible to remove the need for initial guesses entirely and rely on the bounds, but the stability of the Secant method could cause it to diverge outside of the bounds immediately.
I could add additional tests to for Secant failure specifically if desired. Due to the nature of Secant, it will fail on repeated roots, or when the interval is split perfectly around a root, etc.
> Added RootFinding.Secant and unit tests (based on NewtonRaphson)

- src/Numerics/Distributions/Bernoulli.cs
- src/Numerics/Distributions/Beta.cs
- src/Numerics/Distributions/BetaScaled.cs
- src/Numerics/Distributions/Binomial.cs
- src/Numerics/Distributions/Categorical.cs
- src/Numerics/Distributions/Cauchy.cs
- src/Numerics/Distributions/Chi.cs
- src/Numerics/Distributions/ChiSquared.cs
- src/Numerics/Distributions/ContinuousUniform.cs
- src/Numerics/Distributions/ConwayMaxwellPoisson.cs
- src/Numerics/Distributions/Erlang.cs
- src/Numerics/Distributions/Exponential.cs
- src/Numerics/Distributions/FisherSnedecor.cs
- src/Numerics/Distributions/Geometric.cs
- src/Numerics/Distributions/Hypergeometric.cs
- src/Numerics/Distributions/Laplace.cs
- src/Numerics/Distributions/LogNormal.cs
- src/Numerics/Distributions/MatrixNormal.cs
- src/Numerics/Distributions/Multinomial.cs
- src/Numerics/Distributions/NegativeBinomial.cs
- src/Numerics/Distributions/Normal.cs
- src/Numerics/Distributions/NormalGamma.cs
- src/Numerics/Distributions/Pareto.cs
- src/Numerics/Distributions/Poisson.cs
- src/Numerics/Distributions/Rayleigh.cs
- src/Numerics/Distributions/Stable.cs
- src/Numerics/Distributions/StudentT.cs
- src/Numerics/Distributions/Triangular.cs
- src/Numerics/Distributions/Weibull.cs
- src/Numerics/Statistics/ArrayStatistics.cs
I noticed (while adding a truncated normal distribution) that a bunch of comments where slightly wrong. I don't think anyone would have been confused by them but fixed them anyway.
Comments on some properties on most Distributions incorrectly stated
that they were setters as well.
One comment on an array statistic stated it was returned the smallest
instead of largest member.
> Minor comment corrections

- docs/content/MKL.md
- src/NativeProviders/OSX/mkl_build.sh
Hello,
I've updated the mkl_build script to build the MKL native provider on OSX thanks to directions from @cuda and @cdrnet. I've succeed in building the native provider on my mac and run the example given in the doc (matrix multiplication).
I've also enriched the OSX section of the doc file (MKL.md) so people not familiar with the  build process (like me) can do it themselves more easily.
Lionel
PS : I'm running OSX 10.10.5 with intel Parallel Studio XE 2016 on a macbook pro end 2011 - core i7 2.8 GHz.
> Update mkl native provider for OSX

- src/Numerics/Statistics/Histogram.cs
- src/UnitTests/StatisticsTests/HistogramTests.cs
As described in issue https://github.com/mathnet/mathnet-numerics/issues/323, adding values that are equal to the lower bound of a histogram result in an exception. Values slightly lower than that bound, will decrease the lower bound automatically as required.
Therefore, i propose to initiate this behavior on all values *equal* or lower that the boundary.
> Histogram: Adding data equal to the lower bound

- src/Numerics/Complex32.cs
- src/UnitTests/ComplexTests/Complex32Test.cs
I changed magnitude because of overflow for big numbers, It's now based on simple mathematical observation that Sqrt(a^2+b^2) = |a| * Sqrt(1+b/a*b/a). 
Problem with squaring might occur for example when we had a or b bigger than (2 *10^19) because of (2 *10^19)^2 == 4 *10^38 > 3.4 *10^38 == float.MaxValue.  
Second change is in division. Now there will be no Nan or overflow when dividing two numbers with real/imaginary values near float.epsilon. It's based on Smith's algorithm but is enhanced because Smith's sometimes returned bad imaginary values. 
For more examples see unit test in my commit.
> More accurate algorithms for Complex

- src/Numerics/SpecialFunctions/Erf.cs
In response to issue #365 I moved the many polynomial coefficient arrays to static fields for all implementations of Erf, Erfc, ErfInv over all input values.  I made the comments and field names similar to those in ModifiedBessel.cs.  No functionality is added or removed.
> Make the coefficient arrays for ErfImp and ErfInvImp static fields.

- src/Numerics/Control.cs
Moved initialization of default LinearAlgebraProvider out of Control.ConfigureAuto to prevent unnecessary initialization and exceptions. Initialization code moved to new method, InitializeDefaultLinearAlgebraProvider(), which is called from the LinearAlgebraProvider getter only if the current _linearAlgebraProvider is null. This prevents trying to initialize multiple providers when calling any of the 'UseXX' methods.
> Moved initialization of LinearAlgebraProvider to reduce exceptions

- build/NativeProvider.targets
Suppose Lib1 is a C# project which uses the NuGet package containing the native dll, and Lib2 depends on Lib1, and finally Lib3 depends on Lib2.  With the current setup, the native dlls will be copied into the output directory of both Lib1 and Lib2, but not Lib3.  Using 'None' instead of 'Content' fixes this.
I don't have a reference for this behaviour, but I have replicated it with three dummy projects to be sure.  I originally got the hint from Benoit Blanchon's comment at http://stackoverflow.com/questions/19478775/
> Fix indirect dependencies on native dlls

- src/Numerics/Optimization/BfgsMinimizer.cs
- src/UnitTests/OptimizationTests/RosenbrockFunction.cs
- src/UnitTests/OptimizationTests/TestBfgsMinimizer.cs
Fixed typo in TestBfgsMinimizer.FindMinimum_BigRosenbrock_Hard() and added static property to avoid future similar typos
> Fixed typo in TestBfgsMinimizer.FindMinimum_BigRosenbrock_Hard()

- src/Numerics/Distributions/ChiSquared.cs
I noticed a bug in the generation of ChiSquared samples. Probably left from copy-pasting code from Chi.cs
> fixed generation of ChiSquared Samples

- src/Numerics/Random/RandomSource.cs
- src/UnitTests/Random/RandomTests.cs
I added two special cases:
* when 0 bits should be sampled, alsways return 0
* when an int should be sampled with an exclusive maximum of 1, always return 0
This should fix Issue #427 .
I also added a new test, if the boundaries are respected when calling Next(). I'm not  completely sure it's in the right place though.
> Fix for Issue #427

- src/Numerics/Numerics.csproj
- src/Numerics/Optimization/ObjectiveFunctions/ForwardDifferenceGradientObjectiveFunction.cs
- src/UnitTests/OptimizationTests/BfgsBMinimizerTests.cs
Added objective function adapter that can be used to calculate gradients by forward finite difference if an analytical gradient is not available.
> Optimization: add finite difference objective function adapter

- src/Numerics/OdeSolvers/RungeKutta.cs
The multiplication by the time-step was missing in this method (but not the others)
> Fix multivariate Runge-Kutta ODE solver typo

- src/Numerics/LinearAlgebra/Complex/Matrix.cs
- src/Numerics/LinearAlgebra/Complex/Vector.cs
- src/Numerics/LinearAlgebra/Complex32/Matrix.cs
- src/Numerics/LinearAlgebra/Complex32/Vector.cs
- src/Numerics/LinearAlgebra/Double/Matrix.cs
- src/Numerics/LinearAlgebra/Double/Vector.cs
- src/Numerics/LinearAlgebra/Matrix.Arithmetic.cs
- src/Numerics/LinearAlgebra/Matrix.Operators.cs
- src/Numerics/LinearAlgebra/Single/Matrix.cs
- src/Numerics/LinearAlgebra/Single/Vector.cs
- src/Numerics/LinearAlgebra/Vector.Arithmetic.cs
- src/Numerics/LinearAlgebra/Vector.Operators.cs
Discussion thread is here:  http://discuss.mathdotnet.com/t/any-interests-in-element-wise-operations-on-vector-matrix-with-f/367
> Any interests in element wise operations on vector/matrix with F#?

- src/FSharpUnitTests/FindRootsTests.fs
- src/Numerics/RootFinding/Bisection.cs
- src/UnitTests/RootFindingTests/BisectionTest.cs
At the moment Bisection.FindRoot would iterate until it converges on the maximally precise answer, basically ignoring the "accuracy" attribute. I am using this routine to find a root of a function which is computationally complex, hence every extra invocation matters in my case.
The reason for the incorrect handling of the accuracy lies in the rather strange code at line 111 of the current Bisection.cs:
```
if (Math.Abs(fmax - fmin) < 0.5*accuracy && upperBound.AlmostEqualRelative(lowerBound))
```
As you see this requires the algorithm to run all the way until upperBound equals lowerBound, not until the requested accuracy margin is achieved.
There is another problem: the function makes two accuracy tests at the very beginning. The tests are of the following type:
```
if (Math.Abs(fmin) < …
```
> Fixed accuracy handling in RootFinding.Bisection

- src/Numerics/ComplexExtensions.cs
- src/Numerics/IntegralTransforms/Fourier.Bluestein.cs
- src/Numerics/IntegralTransforms/Fourier.Naive.cs
- src/Numerics/IntegralTransforms/Fourier.RadixN.cs
- src/Numerics/IntegralTransforms/Fourier.cs
- src/Numerics/Providers/FourierTransform/IFourierTransformProvider.cs
- src/Numerics/Providers/FourierTransform/ManagedFourierTransformProvider.cs
- src/Numerics/Providers/FourierTransform/Mkl/MklFourierTransformProvider.cs
- src/UnitTests/IntegralTransformsTests/FourierTest.cs
- src/UnitTests/IntegralTransformsTests/InverseTransformTest.cs
- src/UnitTests/IntegralTransformsTests/MatchingNaiveTransformTest.cs
- src/UnitTests/IntegralTransformsTests/ParsevalTheoremTest.cs
Duplicated existing double precision Fourier Transform code for single precision. This includes unit tests, managed provider and MKL provider.
> Single precision Fourier Transform support

- src/Numerics/Statistics/RunningStatistics.cs
This prevents most of the fields from being set to NaN when merging an empty instance.
> Handle combining empty running statistics

- src/Numerics/LinearAlgebra/Complex/Factorization/DenseCholesky.cs
- src/Numerics/LinearAlgebra/Complex/Factorization/UserCholesky.cs
- src/Numerics/LinearAlgebra/Complex32/Factorization/DenseCholesky.cs
- src/Numerics/LinearAlgebra/Complex32/Factorization/UserCholesky.cs
- src/Numerics/LinearAlgebra/Double/Factorization/DenseCholesky.cs
- src/Numerics/LinearAlgebra/Double/Factorization/UserCholesky.cs
- src/Numerics/LinearAlgebra/Factorization/Cholesky.cs
- src/Numerics/LinearAlgebra/Single/Factorization/DenseCholesky.cs
- src/Numerics/LinearAlgebra/Single/Factorization/UserCholesky.cs
- src/UnitTests/LinearAlgebraTests/Complex/Factorization/CholeskyTests.cs
- src/UnitTests/LinearAlgebraTests/Complex/Factorization/UserCholeskyTests.cs
- src/UnitTests/LinearAlgebraTests/Complex32/Factorization/CholeskyTests.cs
- src/UnitTests/LinearAlgebraTests/Complex32/Factorization/UserCholeskyTests.cs
- src/UnitTests/LinearAlgebraTests/Double/Factorization/CholeskyTests.cs
- src/UnitTests/LinearAlgebraTests/Double/Factorization/UserCholeskyTests.cs
- src/UnitTests/LinearAlgebraTests/Single/Factorization/CholeskyTests.cs
- src/UnitTests/LinearAlgebraTests/Single/Factorization/UserCholeskyTests.cs
Allows factorization with re-use of an existing factor matrix, and corresponding implementations and unit tests.
Partially addresses issue #431
> Added method 'Factorize' to 'Cholesky' base class

- src/Numerics/SpecialFunctions/Beta.cs
Changed the number of iterations for the loop from 140 to 50,000 in the BetaRegularized method. This brought the result of 
```
MathNet.Numerics.SpecialFunctions.BetaRegularized(6985172036240.918, 5029323866093.4609, 0.581395348837209);
``` 
to 0.5101 which seem to agree with the results given by R(0.5) and Mathematica(0.495).
> BetaRegularized Fix - Issue 491

- src/FSharp/FindRoots.fs
- src/FSharpUnitTests/FindRootsTests.fs
- src/Numerics/RootFinding/Broyden.cs
- src/UnitTests/RootFindingTests/BroydenTest.cs
I noticed that Broyden method fails to find the root in some cases. To my knowledge, the reason for this is that the step size for calculating the Jacobian matrix can become smaller than the machine epsilon. This causes the Jacobian matrix to be singular.
Two changes were made to the Broyden method to fix the issue:
1. Added the possibility to give the step size for calculating the approximate Jacobian as a parameter. Optional parameter is added to method FindRoot and alternative method TryFindRootWithJacobianStep is added.
2. Changed the formula for step size to be h = (1.0 + Abs(x))*stepSize instead of Abs(x)*stepSize. This fixes the problem with too small step size and is in line with the implementation in NumericalDerivative class.
A unit test demonstrating the failure is added. Also …
> Initial Jacobian of Broyden method

- src/Numerics/LinearAlgebra/Complex/Solvers/MlkBiCgStab.cs
- src/Numerics/LinearAlgebra/Complex32/Solvers/MlkBiCgStab.cs
- src/Numerics/LinearAlgebra/Double/Solvers/MlkBiCgStab.cs
- src/Numerics/LinearAlgebra/Single/Solvers/MlkBiCgStab.cs
This uses the capacity overload of the `List` constructor as we know that `orthogonalMatrix.ColumnCount` entries will be inserted.
> Initialize list with known capacity

- src/Numerics/Distance.cs
- src/Numerics/Optimization/NelderMeadSimplex.cs
- src/Numerics/Providers/LinearAlgebra/ManagedLinearAlgebraProvider.Complex.cs
`Jaccard` already throws if `a` or `b` is null, so no need to check them again.
And if the null initial null checks weren't there, `a.Length` or `b.Length` could throw an `NRE` before `(a == null && b == null)` was called
`Minimum` checked `initialGuess` twice instead of checking `initalPertubation`.
`AddVectorToScaledVector` checked `if (y.Length != x.Length)` twice.
> Argument checks

- src/Numerics/LinearAlgebra/Complex/Solvers/ILUTPPreconditioner.cs
This saves a call to `knownPivots` by using `TryGetValue` instead of using `ContainsKey` and the dictionary indexer.
> Use TryGetValue instead of ContainsKey+indexer

- src/Numerics.Tests/Random/Xoshiro256StarStarTests.cs
- src/Numerics/Random/Xoshiro256StarStar.cs
This PRNG is the most recent evolution of Marsaglia's xorshift. It passes all known statistical tests, is fast to compute, has only 256 bits of state, and has good (and provable) distribution. 
[xoshiro / xoroshiro generators and the PRNG shootout](http://xoshiro.di.unimi.it/)
[Scrambled Linear Pseudorandom Number Generators](https://arxiv.org/abs/1805.01407)
> Added a new RandomSource: Xoshiro256StarStar.

- src/Numerics.Tests/SpecialFunctionsTests/BesselTests.cs
- src/Numerics.Tests/SpecialFunctionsTests/KelvinTests.cs
- src/Numerics/Constants.cs
- src/Numerics/SpecialFunctions/Airy.cs
- src/Numerics/SpecialFunctions/Bessel.cs
- src/Numerics/SpecialFunctions/Hankel.cs
- src/Numerics/SpecialFunctions/Kelvin.cs
- src/Numerics/SpecialFunctions/Options.cs
- src/Numerics/SpecialFunctions/SphericalBessel.cs
PR according to the discussion in #601. 
1. `Scale` enum was added and used instead of the `expScaled` boolean flag.
2. Scaled Bessel functions were added separately.
3. `HankelH1` and `HankelH2` return usually complex values, so their real argument functions were removed.
4. Scaling options were removed from `SphericalBesselJ` and `SphericalBesselY`. - It is hard to find libraries that supports scaled spherical Bessel functions.
`Scaled` prefix was used temporarily for exponentially scaled Bessel functions. Please suggest me a better suffix or prefix.
> Special Functions: cleanup Bessel-type functions

- src/Numerics/Optimization/NelderMeadSimplex.cs
Immediately prior to completion, re-evaluate objective function with best vertex to set proper state.
> Issue 632, NelderMeadSimplex Does Not Always Return Best Evaluated Point

- docs/content/Build.md
Since Google+ is shut down, broken Google+ link is removed.
> Removed broken Google+ link.

- src/Numerics/Distributions/Hypergeometric.cs
This is, to be fair, a kludge -- it would be more efficient to ensure that such a situation can never arise in the first place. Proposed as a temporary(?) solution to issue #679
> Ensure Hypergeometric.CDF <= 1.0 (Issue #679)

- src/Numerics.Tests/DistributionTests/Discrete/GeometricTests.cs
> Fix GeometricTests.ValidateProbabilityLn to use expected value parameter

- src/Numerics.Tests/DistributionTests/Continuous/RayleighTests.cs
Fix `RayleightTests.ValidateMaximum` test to use the scale parameter instead of the hardcoded value.
Fix #708
> Fix RayleightTests.ValidateMaximum test to use testcase parameter

- src/Numerics.Tests/LinearAlgebraTests/Complex/DenseMatrixTests.cs
- src/Numerics.Tests/LinearAlgebraTests/Complex/DiagonalMatrixTests.cs
- src/Numerics.Tests/LinearAlgebraTests/Complex/MatrixTests.Arithmetic.cs
- src/Numerics.Tests/LinearAlgebraTests/Complex/SparseMatrixTests.cs
- src/Numerics.Tests/LinearAlgebraTests/Complex/VectorTests.cs
- src/Numerics.Tests/LinearAlgebraTests/Complex32/DenseMatrixTests.cs
- src/Numerics.Tests/LinearAlgebraTests/Complex32/DiagonalMatrixTests.cs
- src/Numerics.Tests/LinearAlgebraTests/Complex32/MatrixTests.Arithmetic.cs
- src/Numerics.Tests/LinearAlgebraTests/Complex32/SparseMatrixTests.cs
- src/Numerics.Tests/LinearAlgebraTests/Complex32/VectorTests.cs
- src/Numerics.Tests/LinearAlgebraTests/Double/DenseMatrixTests.cs
- src/Numerics.Tests/LinearAlgebraTests/Double/DiagonalMatrixTests.cs
- src/Numerics.Tests/LinearAlgebraTests/Double/MatrixTests.Arithmetic.cs
- src/Numerics.Tests/LinearAlgebraTests/Double/SparseMatrixTests.cs
- src/Numerics.Tests/LinearAlgebraTests/Double/VectorTests.cs
- src/Numerics.Tests/LinearAlgebraTests/MatrixStructureTheory.Access.cs
- src/Numerics.Tests/LinearAlgebraTests/MatrixStructureTheory.cs
- src/Numerics.Tests/LinearAlgebraTests/MatrixTests.cs
- src/Numerics.Tests/LinearAlgebraTests/Single/DenseMatrixTests.cs
- src/Numerics.Tests/LinearAlgebraTests/Single/DiagonalMatrixTests.cs
- src/Numerics.Tests/LinearAlgebraTests/Single/MatrixTests.Arithmetic.cs
- src/Numerics.Tests/LinearAlgebraTests/Single/SparseMatrixTests.cs
- src/Numerics.Tests/LinearAlgebraTests/Single/VectorTests.cs
- src/Numerics.Tests/LinearAlgebraTests/VectorTests.cs
- src/Numerics/LinearAlgebra/Storage/DenseVectorStorage.cs
- src/Numerics/LinearAlgebra/Storage/MatrixStorage.cs
- src/Numerics/LinearAlgebra/Storage/SparseVectorStorage.cs
- src/Numerics/LinearAlgebra/Storage/VectorStorage.cs
Fix #134 
This is an attempt at allowing empty (zero-length) `Vector` and `Matrix`. I am relying on the existing tests to find any issue with what I have done as I am not enough of an expert to see if there are any unwanted consequences.
> Allow empty Vector and Matrix

- src/Numerics.Tests/PolynomialTests.cs
- src/Numerics/Polynomial.cs
Fixes #730 - the two cases mentioned in the original issue description. 
For polynomial evaluation, the issue affected a few variants of the API (double vs Complex), hopefully all are fixed and properly tested now.
Looking forward to getting this pulled and included in a release, so that I can get rid of the workarounds in my project. A big fan of Math.NET, and actually this was the first time it misbehaved... Keep it up!
> Fix for #730 - a few operations broken on zero polynomials

- src/Data/Matlab/Formatter.cs
- src/Data/Matlab/Parser.cs
I inlined the strings that were in the resources of Mathnet.Numerics in the Versions lower than 4.12.
This should fix Issue https://github.com/mathnet/mathnet-numerics/issues/727
This is my first PR, so please be gentle.
> Removed Dependency to Mathnet.Numerics.Properties Resources

- src/Numerics/Optimization/GoldenSectionMinimizer.cs
Recompute the middle point for each iteration to avoid loss of precision.
> Updated golden section minimizer to avoid precision loss

- docs/content/Interpolation.md
- src/Numerics.Tests/InterpolationTests/PchipSplineTest.cs
- src/Numerics/Interpolate.cs
- src/Numerics/Interpolation/CubicSpline.cs
Added PCHIP (piecewise cubic Hermite interpolating polynomial).
This is a somewhat popular request on the [feedback forum](http://feedback.mathdotnet.com/forums/2060-math-net-numerics/suggestions/15436-implement-matlab-s-pchip-interpolation-algorithm).
The algorithm is based on that in "Numerical Computing with MATLAB" (Clive Moler).
I'm not so sure about the name, however.
Matlab/Octave and SciPy call this pchip, NAG calls this monotonic_interpolant while the original paper by Fritsch and Carlson (1980) is titled "Monotone Piecewise Cubic Interpolation".
> Added PCHIP

- src/Numerics/Distributions/Cauchy.cs
- src/Numerics/Interpolation/CubicSpline.cs
- src/Numerics/Precision.Equality.cs
Couple of minor changes, mainly for performance, given how (relatively) slow Math.Pow() tends to be.
Might be worth having a seperate optimized class for common power operators like Pow2(), Pow10(), Square(), Cube()
> Minor performance

- src/Numerics.Tests/OptimizationTests/BfgsMinimizerTests.cs
- src/Numerics/Optimization/QuadraticGradientProjectionSearch.cs
Fixed an index out of bounds issue when calculating BFGS minimizer with one variable.
Moved a check to the start of a loop in QuadraticGradientProjectionSearch so that we exit earlier with one variable, and added a test that would have caught this issue.
Fixes github issue #510
> Fix issue 510

- src/Numerics.Tests/Random/RandomTests.cs
- src/Numerics/Random/Xoshiro256StarStar.cs
Fixes an OutOfRangeException thrown by the xoshiro256** implementation of DoSampleBytes when passed certain length buffers.
Also adds a related test for all random implementations to ensure they don't throw exceptions when calling NextBytes based on the length of the buffer. For xoshiro256** an OOR occurred depending on the buffer length mod 8.
- All PRNGs are passing the new test.
Fixes #664
> Resolve xoshiro256** out of range exception

- src/Numerics.Tests/Random/RandomExtensionTests.cs
- src/Numerics/Random/RandomExtensions.cs
I found a boundary condition that falls into an infinite loop. Fixed.
> Fix infinite loop in RandomExtensions.NextBigIntegerSequence(0,1)

- src/Numerics.Tests/LinearAlgebraTests/MatrixTests.cs
- src/Numerics/LinearAlgebra/Double/SparseMatrix.cs
The result of pointwise multiplication and division on sparse matrices is passed as an argument. The result is cleared without checking if it is equal to the current instance, thus causing a full deletion of the sparse matrix contents.
(Fixes bug "Inconsistency with PointwiseMultiplication for SparseMatrix #776")
> Pointwise multiplication and division on sparse matrices

- src/Data.Tests/Text/DelimitedWriterTests.cs
- src/Numerics.Tests/LinearAlgebraTests/MatrixHelpers.cs
The changes ensure that the unit tests pass on locales that do not use the period as decimal separator
> Explicitly specify invariant culture in some unit tests

- RELEASENOTES.md
- src/Numerics.Tests/LinearAlgebraTests/Double/DenseMatrixTests.cs
- src/Numerics/LinearAlgebra/Matrix.BCL.cs
Fixes crashes for matrices whose dimension can be zero (fixes #775 )
> Bug in string description for mx0 and 0xn matrices

- src/Numerics.Tests/SpecialFunctionsTests/MittagLefflerTests.cs
- src/Numerics/SpecialFunctions/MittagLeffler.cs
The Mittag-Leffler functions were added:
- Mittag-Leffler function: E_(α)(z) = sum_(k=0)^∞ z^k/Γ(k α + 1)
- generalized Mittag-Leffler function: E_(α, β)(z) = sum_(k=0)^∞ z^k/Γ(k α + β)
- three-parameter Mittag-Leffler function: E_(α, β, γ)(z) = sum_(k=0)^∞ (z^k Γ(k + γ))/(k! Γ(γ) Γ(k α + β))
I translated [Professor Robert Garrappa's Matlab code](https://www.mathworks.com/matlabcentral/fileexchange/48154-the-mittag-leffler-function) (BSD-3-Clause).
> Special Functions: add Mittag-Leffler function

- src/NativeProviders/Linux/mkl_build.sh
- src/NativeProviders/Linux/readme.txt
I'm using MathNet with MKL on Linux. I had to make these changes to build with the latest MKL.
The current MKL for Linux library in the nugget package is too old and MathNet doesn't accept it.
> MKL linux build

- src/Numerics.Tests/IntegrationTests/IntegrationTest.cs
- src/Numerics/Integrate.cs
- src/Numerics/Integration/GaussLegendreRule.cs
I've recently encountered the need to perform triple integration over tetrahedral regions. To address this, I've added a very simple yet convenient 3D integral method to the `GaussLegendreRule` class.
Regarding the method name, since the 2D integration method is called `OnRectangle`, I've named the 3D integration method `OnCuboid`. However, I'm uncertain if this name is appropriate.
> Integration: Add triple integral

- src/Numerics/LinearAlgebra/Complex/Factorization/Svd.cs
- src/Numerics/LinearAlgebra/Complex32/Factorization/Svd.cs
- src/Numerics/LinearAlgebra/Double/Factorization/Svd.cs
- src/Numerics/LinearAlgebra/Factorization/Svd.cs
- src/Numerics/LinearAlgebra/Single/Factorization/Svd.cs
> Change documentation of Svd.Determinant properties

- docs/MatlabFiles.md
The "MatlabWrier" should be "MatlabWriter".
> Fix typo in MatlabFiles.md

- src/Numerics.Tests/SpecialFunctionsTests/SpecialFunctionsTests.cs
- src/Numerics/SpecialFunctions/Stability.cs
> Fix SpecialFunctions.Hypotenuse when elements are double.NaN

- src/Numerics/LinearAlgebra/Double/SparseMatrix.cs
The result vector needs to be zeroed before contributions from the non-zero elements of the sparse matrix are added to it.
> Fix initialisation bug in sparse matrix DoTransposeThisAndMultiply operation

- src/Numerics.Tests/InterpolationTests/MakimaSplineTest.cs
- src/Numerics/Interpolation/CubicSpline.cs
This pull request introduces support for Modified Akima (Makima) interpolation within the CubicSpline class.
The implementation leverages SciPy’s modified Akima algorithm by computing weighted slopes with adjusted weights to reduce overshoot.
> Add Makima (Modified Akima) Interpolation to CubicSpline

- src/Numerics/Optimization/LevenbergMarquardtMinimizer.cs
> Fix LevenbergMarquardtMinimizer stopping condition
